FROM ghcr.io/dbt-labs/dbt-bigquery:1.3.0

ARG DBT_PROJECT
ARG DBT_DATASET
ARG DBT_PROFILES_DIR

ENV DBT_PROJECT=${DBT_PROJECT}
ENV DBT_DATASET=${DBT_DATASET}
ENV DBT_PROFILES_DIR=${DBT_PROFILES_DIR}

WORKDIR /usr/app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir dbt-serverless

COPY ${DBT_PROJECT}/ ${DBT_PROFILES_DIR}/profiles.yml ${DBT_PROJECT}/

ENTRYPOINT ["uvicorn", "dbt_serverless.main:app", "--host", "0.0.0.0", "--port", "8080"]
